#!/bin/sh

set -eu

# Run `gengetoptions embed` command after changing the `parser_definition` function:
# 	`make gengetoptions`

# @getoptions
# shellcheck disable=SC2329
parser_definition() {
	setup _rf_unknown_args help:usage plus:false no:false error:_rf_error -- \
		"Usage: run_for.sh {-c|--command <string>} [-s|--seconds <number>]" \
		"		[-q|--quiet][-v|--verbose][-V|--version][-h|--help]" ''
	msg -- 'Options:'
	param _rf_seconds -s --seconds var:SECONDS init:=60 validate:_rf_validate_seconds -- "seconds to wait for script to exit [default: 60]"
	param _rf_command -c --command var:COMMAND validate:_rf_is_string_empty mandatory:true -- "command to be executed {mandatory}"
	flag _rf_quiet -q --quiet var:QUIET init:=false on:true no:false -- "don't output any status messages from 'run_for.sh' script"
	flag _rf_verbose -v --verbose var:VERBOSE init:=false on:true no:false -- "increase verbosity"
	disp VERSION -V --version -- "print the 'run_for.sh' script version"
	disp :usage -h --help -- "show this help"
}
# @end

# Error messages:
#   $1: Default error message
#   $2: Error name
#     - `unknown` (Unrecognized option)
#     - `noarg` (Does not allow an argument)
#     - `required` (Requires an argument)
#     - `pattern:<PATTERN>` (Does not match the pattern)
#     - `validator_name:<STATUS>` (Validation error)
#     - `ambiguous` (Ambiguous option)
#   $3: Option
#   $4-: Validator name and arguments (if $2 is validator_name)
#   $4-: Candidate options (if $2 is ambiguous)
#   return: exit status

# @parser start
# Custom error handler
_rf_error() {
	case $2 in
	_rf_validate_seconds:1) sixlogger fatal "Not a valid number: ${3} '${OPTARG}'" ;;
	_rf_validate_seconds:2) sixlogger fatal "Script must run for at least 1 second" ;;
	_rf_is_string_empty:1) sixlogger fatal "Argument '${3}' is empty: '${OPTARG}'" ;;
	*) return 0 ;; # Display default error
	esac
	return 1
}

# Custom validate functions
_rf_validate_seconds() {
	# Cannot be empty string
	_rf_is_string_empty || return 1
	# Has to be a number
	case $OPTARG in *[!0-9]*) return 1 ;; esac
	# Has to be >= 1
	[ "$OPTARG" -ge 1 ] || return 2
}

_rf_is_string_empty() {
	awk \
		-v str="$OPTARG" \
		-v regex='^\\s*\\S.*$' \
		'BEGIN{ exit match(str, regex) == 0 }'
}

# @gengetoptions parser -i parser_definition parse
# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.2)
_rf_seconds='60'
_rf_command=''
_rf_quiet='false'
_rf_verbose='false'
_rf_unknown_args=''
# shellcheck disable=SC2004
parse() {
	OPTIND=$(($# + 1))
	while OPTARG= && [ "${_rf_unknown_args}" != x ] && [ $# -gt 0 ]; do
		case $1 in
		--?*=*)
			OPTARG=$1
			shift
			eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
			;;
		--no-* | --without-*) unset OPTARG ;;
		-[sc]?*)
			OPTARG=$1
			shift
			eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
			;;
		-[qvVh]?*)
			OPTARG=$1
			shift
			eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
			case $2 in --*) set -- "$1" unknown "$2" && _rf_unknown_args=x ;; esac
			OPTARG=
			;;
		+*) unset OPTARG ;;
		esac
		case $1 in
		'-s' | '--seconds')
			[ $# -le 1 ] && set "required" "$1" && break
			OPTARG=$2
			_rf_validate_seconds || {
				set -- _rf_validate_seconds:$? "$1" _rf_validate_seconds
				break
			}
			_rf_seconds="$OPTARG"
			shift
			;;
		'-c' | '--command')
			_c_flag_declared="true"
			[ $# -le 1 ] && set "required" "$1" && break
			OPTARG=$2
			_rf_is_string_empty || {
				set -- _rf_is_string_empty:$? "$1" _rf_is_string_empty
				break
			}
			_rf_command="$OPTARG"
			shift
			;;
		'-q' | '--quiet')
			[ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
			eval '[ ${OPTARG+x} ] &&:' && OPTARG='true' || OPTARG='false'
			_rf_quiet="$OPTARG"
			;;
		'-v' | '--verbose')
			[ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
			eval '[ ${OPTARG+x} ] &&:' && OPTARG='true' || OPTARG='false'
			_rf_verbose="$OPTARG"
			;;
		'-V' | '--version')
			echo "${VERSION}"
			exit 0
			;;
		'-h' | '--help')
			usage
			exit 0
			;;
		--)
			shift
			while [ $# -gt 0 ]; do
				_rf_unknown_args="${_rf_unknown_args} \"\${$(($OPTIND - $#))}\""
				shift
			done
			break
			;;
		[-+]?*)
			set "unknown" "$1"
			break
			;;
		*)
			_rf_unknown_args="${_rf_unknown_args} \"\${$(($OPTIND - $#))}\""
			;;
		esac
		shift
	done
	[ $# -eq 0 ] &&
		[ "${_c_flag_declared:-}" = "true" ] &&
		{
			OPTIND=1
			unset OPTARG
			return 0
		}
	case ${1:-} in
	unknown) set "Unrecognized option: $2" "$@" ;;
	noarg) set "Does not allow an argument: $2" "$@" ;;
	required) set "Requires an argument: $2" "$@" ;;
	pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
	notcmd) set "Not a command: $2" "$@" ;;
	*)
		{ [ -z "${1:-}" ] && [ -z "${_c_flag_declared:-}" ] && set "Mandatory argument: -c" "mandatory -c"; } ||
			set "Validation error ($1): $2" "$@"
		;;
	esac
	_rf_error "$@" >&2 || exit $?
	sixlogger fatal "$1"
	exit 1
}
usage() {
	cat <<'GETOPTIONSHERE'
Usage: run_for.sh {-c|--command <string>} [-s|--seconds <number>]
    [-q|--quiet][-v|--verbose][-V|--version][-h|--help]

Options:
  -s,     --seconds SECONDS   seconds to wait for script to exit [default: 60]
  -c,     --command COMMAND   command to be executed {mandatory}
  -q,     --quiet             don't output any status messages from 'run_for.sh' script
  -v,     --verbose           increase verbosity
  -V,     --version           print the 'run_for.sh' script version
  -h,     --help              show this help
GETOPTIONSHERE
}
# Generated by getoptions (END)
# @end
# @parser end
